# Site settings
title: Thor the mighty!
description: "Notes to myself"
baseurl: ""
url: "http://blog.idursun.com"
twitter: idursun
github : idursun
username: idursun

# Build settings
markdown: kramdown
permalink: pretty
