# Site settings
title: Thor the mighty!
email: ibrahim.dursun@gmail.com
description: "Personal blog"
baseurl: ""
url: "http://blog.idursun.com"
twitter: idursun
github : idursun
username: idursun

# Build settings
markdown: kramdown
permalink: pretty
